# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ptyline < Formula
  desc "Lightweight terminal wrapper with a configurable bottom status bar"
  homepage "https://github.com/HSGiGa/ptyline"
  version "0.9.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/HSGiGa/ptyline/releases/download/v0.9.3/ptyline-darwin-arm64.tar.gz"
      sha256 "60d0eaea373f1eee6ce2e8bf75bcd80deef3db08cf3ed26f9328a5cb55c4c1fd"

      define_method(:install) do
        bin.install "ptyline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/HSGiGa/ptyline/releases/download/v0.9.3/ptyline-linux-amd64.tar.gz"
      sha256 "07955463af4849c636d84fc816350060063a9b8d5b43c6b37e1fc96509d1b9d1"
      define_method(:install) do
        bin.install "ptyline"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HSGiGa/ptyline/releases/download/v0.9.3/ptyline-linux-arm64.tar.gz"
      sha256 "676c994d570042765169ecdcf603ab07152a7e77eda429b7297f34fd7831e210"
      define_method(:install) do
        bin.install "ptyline"
      end
    end
  end

  def caveats
    <<~EOS
      On first run ptyline writes an editable config to
      ~/.config/ptyline/config.toml. Themes and styles are built in, so
      it works out of the box; drop your own into ~/.config/ptyline/themes
      or styles to override them.
      See https://github.com/HSGiGa/ptyline#configuration.
    EOS
  end

  test do
    assert_match "ptyline", shell_output("#{bin}/ptyline --version")
  end
end
