# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ptyline < Formula
  desc "Lightweight terminal wrapper with a configurable bottom status bar"
  homepage "https://github.com/HSGiGa/ptyline"
  version "0.9.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/HSGiGa/ptyline/releases/download/v0.9.1/ptyline-darwin-arm64.tar.gz"
      sha256 "4c556cfe6712f43d1f4d9a06b48a8e888064ed536e151e5c4422e71a6dd6c0a9"

      define_method(:install) do
        bin.install "ptyline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/HSGiGa/ptyline/releases/download/v0.9.1/ptyline-linux-amd64.tar.gz"
      sha256 "b95ca2a26bfc29d4bc1e8ce66063dc896e1aff1594171f8a34dc6932f720925e"
      define_method(:install) do
        bin.install "ptyline"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HSGiGa/ptyline/releases/download/v0.9.1/ptyline-linux-arm64.tar.gz"
      sha256 "fbab5f2e674c712080d16579f890f6e869b766c3aea180a2c3734805b0678c7a"
      define_method(:install) do
        bin.install "ptyline"
      end
    end
  end

  def caveats
    <<~EOS
      On first run ptyline writes an editable config to
      ~/.config/ptyline/config.toml. Themes and styles are built in, so
      it works out of the box; drop your own into ~/.config/ptyline/themes
      or styles to override them.
      See https://github.com/HSGiGa/ptyline#configuration.
    EOS
  end

  test do
    assert_match "ptyline", shell_output("#{bin}/ptyline --version")
  end
end
