# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ptyline < Formula
  desc "Lightweight terminal wrapper with a configurable bottom status bar"
  homepage "https://github.com/HSGiGa/ptyline"
  version "0.9.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/HSGiGa/ptyline/releases/download/v0.9.6/ptyline-darwin-arm64.tar.gz"
      sha256 "a4c7569648f1d8905232bc0d8817197853145018aba6614a4a95bc20ce052e3e"

      define_method(:install) do
        bin.install "ptyline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/HSGiGa/ptyline/releases/download/v0.9.6/ptyline-linux-amd64.tar.gz"
      sha256 "cd74394a7b24e12aef9b27c6b54acaaf3456dff5f7705072e5d77ee51bc4284b"
      define_method(:install) do
        bin.install "ptyline"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HSGiGa/ptyline/releases/download/v0.9.6/ptyline-linux-arm64.tar.gz"
      sha256 "9f95bf1be2ee7fb2357574634696023f677acc8707839a85cee093312cdc343f"
      define_method(:install) do
        bin.install "ptyline"
      end
    end
  end

  def caveats
    <<~EOS
      On first run ptyline writes an editable config to
      ~/.config/ptyline/config.toml. Themes and styles are built in, so
      it works out of the box; drop your own into ~/.config/ptyline/themes
      or styles to override them.
      See https://github.com/HSGiGa/ptyline#configuration.
    EOS
  end

  test do
    assert_match "ptyline", shell_output("#{bin}/ptyline --version")
  end
end
